server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: first-microservice
          uri: http://localhost:8081/
          predicates:
            - Path=/first/**
        - id: second-microservice
          uri: http://localhost:8082/
          predicates:
            - Path=/second/**
        - id: user-profile
          uri: http://127.0.0.1:3000
          predicates:
            - Path=/rails/**